### ISSUE TITLE
I want to add more than 3 colors to the arc

### ISSUE THREAD

**Issue by saleemnasa** [recogizer/angular-gauge-chart#6]
how to add more than three colors to the arc in angular 6 application?

**Comment by mmaltsev** [comment]
Hi @saleemnasa!

I guess that the reason behind your issue is that you have only two `arcDelimiters` specified. The length of the `arcDelimiters` list should always be less then the length of `arcColors` by one.

Try the following options:
```
this.options = {
      arcColors: ['lightblue', 'lightgreen', 'lightcoral', 'lightgray', 'lightsalmon'],
      arcDelimiters: [20, 40, 60, 80],
      rangeLabel: ['0', '100'],
    }
```
<img src="https://user-images.githubusercontent.com/8640432/43196357-ec4c0248-9007-11e8-84a9-ff277e7e1bb0.png" width="320" height="300">

**Comment by saleemnasa** [comment]
Hi @mmaltsev ,
wow it worked..
I think I didn't understood the "arcDelimiters" values.
now I got it.


Thanks for your reply. :) 👍
